### ISSUE TITLE
Comma broken application

### ISSUE THREAD

**Issue by lguilhermecardoso** [rstriquer/laravel_angular_youtube#1]
this comma breaks your json.file

https://github.com/rstriquer/laravel_angular_youtube/blob/0bf3d744ec8dc92074c26213bb9036d72603214e/server/composer.json#L15

**Comment by rstriquer** [comment]
Hi @bijow I just noticed the issue! I do not know the reason but I believe I did not receive any notification from github for this issue.

Anyway, I am much obliged for you to point that bug. I'll post the fix in a few min.

Feel free to point out anything else. Cheers.
